# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import src.IntelligentStockMarketAPI
from src.IntelligentStockMarketAPI.models.eod_stock_list_response import EODStockListResponse  # noqa: E501
from src.IntelligentStockMarketAPI.rest import ApiException

class TestEODStockListResponse(unittest.TestCase):
    """EODStockListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EODStockListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = src.IntelligentStockMarketAPI.models.eod_stock_list_response.EODStockListResponse()  # noqa: E501
        if include_optional :
            return EODStockListResponse(
                message = '0', 
                payload = [
                    src.IntelligentStockMarketAPI.models.eod_stock.EODStock(
                        adjusted_close = 56, 
                        close = 56, 
                        code = '0', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        high = 56, 
                        low = 56, 
                        market_capitalization = 56, 
                        name = '0', 
                        open = 56, 
                        previous_close = 56, 
                        type = '0', 
                        volume = 56, )
                    ], 
                status = True
            )
        else :
            return EODStockListResponse(
        )

    def testEODStockListResponse(self):
        """Test EODStockListResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
