# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import src.IntelligentStockMarketAPI
from src.IntelligentStockMarketAPI.api.fundamentals_api import FundamentalsApi  # noqa: E501
from src.IntelligentStockMarketAPI.rest import ApiException


class TestFundamentalsApi(unittest.TestCase):
    """FundamentalsApi unit test stubs"""

    def setUp(self):
        self.api = src.IntelligentStockMarketAPI.api.fundamentals_api.FundamentalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_fundamental_company_stock_code_get(self):
        """Test case for v1_fundamental_company_stock_code_get

        """
        pass

    def test_v1_fundamental_general_get(self):
        """Test case for v1_fundamental_general_get

        """
        pass

    def test_v1_fundamentals_annual_balance_sheet_filing_date_stock_code_get(self):
        """Test case for v1_fundamentals_annual_balance_sheet_filing_date_stock_code_get

        """
        pass

    def test_v1_fundamentals_company_address_id_fundamental_id_get(self):
        """Test case for v1_fundamentals_company_address_id_fundamental_id_get

        """
        pass

    def test_v1_fundamentals_company_address_stock_stock_code_get(self):
        """Test case for v1_fundamentals_company_address_stock_stock_code_get

        """
        pass

    def test_v1_fundamentals_company_details_id_fundamental_id_get(self):
        """Test case for v1_fundamentals_company_details_id_fundamental_id_get

        """
        pass

    def test_v1_fundamentals_company_details_stock_stock_code_get(self):
        """Test case for v1_fundamentals_company_details_stock_stock_code_get

        """
        pass

    def test_v1_fundamentals_company_insider_transactions_stock_code_stock_code_year_get(self):
        """Test case for v1_fundamentals_company_insider_transactions_stock_code_stock_code_year_get

        """
        pass

    def test_v1_fundamentals_company_valuations_stock_code_stock_code_year_get(self):
        """Test case for v1_fundamentals_company_valuations_stock_code_stock_code_year_get

        """
        pass

    def test_v1_fundamentals_exchange_analyst_rankings_exchange_code_exchange_code_year_get(self):
        """Test case for v1_fundamentals_exchange_analyst_rankings_exchange_code_exchange_code_year_get

        """
        pass

    def test_v1_fundamentals_exchange_outstanding_shares_exchange_code_exchange_code_year_get(self):
        """Test case for v1_fundamentals_exchange_outstanding_shares_exchange_code_exchange_code_year_get

        """
        pass

    def test_v1_fundamentals_financial_statements_by_term_from_to_stock_code_term_get(self):
        """Test case for v1_fundamentals_financial_statements_by_term_from_to_stock_code_term_get

        """
        pass

    def test_v1_fundamentals_financial_statements_company_statement_stock_code_year_get(self):
        """Test case for v1_fundamentals_financial_statements_company_statement_stock_code_year_get

        """
        pass

    def test_v1_fundamentals_financial_statements_exchange_year_exchange_code_year_get(self):
        """Test case for v1_fundamentals_financial_statements_exchange_year_exchange_code_year_get

        """
        pass

    def test_v1_fundamentals_financial_statements_filing_date_ticker_filing_date_stock_code_get(self):
        """Test case for v1_fundamentals_financial_statements_filing_date_ticker_filing_date_stock_code_get

        """
        pass

    def test_v1_fundamentals_financial_statements_ticker_date_range_from_to_stock_code_get(self):
        """Test case for v1_fundamentals_financial_statements_ticker_date_range_from_to_stock_code_get

        """
        pass

    def test_v1_fundamentals_financials_income_statements_statement_id_get(self):
        """Test case for v1_fundamentals_financials_income_statements_statement_id_get

        """
        pass

    def test_v1_fundamentals_highlights_id_fundamental_id_get(self):
        """Test case for v1_fundamentals_highlights_id_fundamental_id_get

        """
        pass

    def test_v1_fundamentals_highlights_stock_stock_code_get(self):
        """Test case for v1_fundamentals_highlights_stock_stock_code_get

        """
        pass

    def test_v1_fundamentals_quarterly_balance_sheet_filing_date_stock_code_get(self):
        """Test case for v1_fundamentals_quarterly_balance_sheet_filing_date_stock_code_get

        """
        pass

    def test_v1_fundamentals_tech_indicators_by_company_stock_code_stock_code_year_get(self):
        """Test case for v1_fundamentals_tech_indicators_by_company_stock_code_stock_code_year_get

        """
        pass

    def test_v1_fundamentals_tech_indicators_by_exchange_exchange_code_exchange_code_year_get(self):
        """Test case for v1_fundamentals_tech_indicators_by_exchange_exchange_code_exchange_code_year_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
