# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import src.IntelligentStockMarketAPI
from src.IntelligentStockMarketAPI.api.stocks_api import StocksApi  # noqa: E501
from src.IntelligentStockMarketAPI.rest import ApiException


class TestStocksApi(unittest.TestCase):
    """StocksApi unit test stubs"""

    def setUp(self):
        self.api = src.IntelligentStockMarketAPI.api.stocks_api.StocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_stock_code_stock_code_get(self):
        """Test case for v1_stock_code_stock_code_get

        """
        pass

    def test_v1_stocks_country_country_get(self):
        """Test case for v1_stocks_country_country_get

        """
        pass

    def test_v1_stocks_currency_currency_get(self):
        """Test case for v1_stocks_currency_currency_get

        """
        pass

    def test_v1_stocks_exchange_code_exchange_code_get(self):
        """Test case for v1_stocks_exchange_code_exchange_code_get

        """
        pass

    def test_v1_stocks_exchange_id_exchange_id_get(self):
        """Test case for v1_stocks_exchange_id_exchange_id_get

        """
        pass

    def test_v1_stocks_get(self):
        """Test case for v1_stocks_get

        """
        pass

    def test_v1_stocks_post(self):
        """Test case for v1_stocks_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
