# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import src.IntelligentStockMarketAPI
from src.IntelligentStockMarketAPI.models.highlights import Highlights  # noqa: E501
from src.IntelligentStockMarketAPI.rest import ApiException

class TestHighlights(unittest.TestCase):
    """Highlights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Highlights
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = src.IntelligentStockMarketAPI.models.highlights.Highlights()  # noqa: E501
        if include_optional :
            return Highlights(
                book_value = 1.337, 
                date_created = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                diluted_eps_ttm = 1.337, 
                dividend_share = 1.337, 
                dividend_yield = 1.337, 
                earnings_share = 1.337, 
                ebitda = 56, 
                eps_estimate_current_quarter = 1.337, 
                eps_estimate_current_year = 1.337, 
                eps_estimate_next_quarter = 1.337, 
                eps_estimate_next_year = 1.337, 
                fundamental_id = '0', 
                growth_profit_ttm = 1.337, 
                market_capitalization = 56, 
                market_capitalization_mln = 56, 
                most_recent_quarter = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                operating_margin_ttm = 1.337, 
                pe_ratio = 1.337, 
                peg_ratio = 1.337, 
                profit_margin = 1.337, 
                quarterly_earnings_growth_yoy = 1.337, 
                quarterly_revenue_growth_yoy = 1.337, 
                return_on_assets_ttm = 1.337, 
                return_on_equity_ttm = 1.337, 
                revenue_per_share_ttm = 1.337, 
                revenue_ttm = 1.337, 
                target_price = 56
            )
        else :
            return Highlights(
        )

    def testHighlights(self):
        """Test Highlights"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
