# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from src.IntelligentStockMarketAPI.configuration import Configuration


class GeneralOfficers(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'fundamental_id': 'str',
        'name': 'str',
        'title': 'str',
        'year_born': 'str'
    }

    attribute_map = {
        'fundamental_id': 'fundamental_id',
        'name': 'name',
        'title': 'title',
        'year_born': 'year_born'
    }

    def __init__(self, fundamental_id=None, name=None, title=None, year_born=None, local_vars_configuration=None):  # noqa: E501
        """GeneralOfficers - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._fundamental_id = None
        self._name = None
        self._title = None
        self._year_born = None
        self.discriminator = None

        if fundamental_id is not None:
            self.fundamental_id = fundamental_id
        if name is not None:
            self.name = name
        if title is not None:
            self.title = title
        if year_born is not None:
            self.year_born = year_born

    @property
    def fundamental_id(self):
        """Gets the fundamental_id of this GeneralOfficers.  # noqa: E501

        a unique id for the General Fundamental Company Data  # noqa: E501

        :return: The fundamental_id of this GeneralOfficers.  # noqa: E501
        :rtype: str
        """
        return self._fundamental_id

    @fundamental_id.setter
    def fundamental_id(self, fundamental_id):
        """Sets the fundamental_id of this GeneralOfficers.

        a unique id for the General Fundamental Company Data  # noqa: E501

        :param fundamental_id: The fundamental_id of this GeneralOfficers.  # noqa: E501
        :type: str
        """

        self._fundamental_id = fundamental_id

    @property
    def name(self):
        """Gets the name of this GeneralOfficers.  # noqa: E501

        Name of officer  # noqa: E501

        :return: The name of this GeneralOfficers.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GeneralOfficers.

        Name of officer  # noqa: E501

        :param name: The name of this GeneralOfficers.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def title(self):
        """Gets the title of this GeneralOfficers.  # noqa: E501

        Title of Company Officer  # noqa: E501

        :return: The title of this GeneralOfficers.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this GeneralOfficers.

        Title of Company Officer  # noqa: E501

        :param title: The title of this GeneralOfficers.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def year_born(self):
        """Gets the year_born of this GeneralOfficers.  # noqa: E501

        Year of Birth  # noqa: E501

        :return: The year_born of this GeneralOfficers.  # noqa: E501
        :rtype: str
        """
        return self._year_born

    @year_born.setter
    def year_born(self, year_born):
        """Sets the year_born of this GeneralOfficers.

        Year of Birth  # noqa: E501

        :param year_born: The year_born of this GeneralOfficers.  # noqa: E501
        :type: str
        """

        self._year_born = year_born

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeneralOfficers):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GeneralOfficers):
            return True

        return self.to_dict() != other.to_dict()
