# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from src.IntelligentStockMarketAPI.configuration import Configuration


class General(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cik': 'str',
        'country_name': 'str',
        'currency': 'str',
        'cusip': 'str',
        'description': 'str',
        'employer_id': 'str',
        'exchange': 'str',
        'fiscal_year_end': 'date',
        'fundamental_id': 'str',
        'gic_group': 'str',
        'gic_industry': 'str',
        'gic_sector': 'str',
        'home_category': 'str',
        'industry': 'str',
        'international_domestic': 'bool',
        'ipo_date': 'date',
        'is_delisted': 'bool',
        'isin': 'str',
        'name': 'str',
        'sector': 'str',
        'stock_symbol': 'str',
        'type': 'str'
    }

    attribute_map = {
        'cik': 'cik',
        'country_name': 'country_name',
        'currency': 'currency',
        'cusip': 'cusip',
        'description': 'description',
        'employer_id': 'employer_id',
        'exchange': 'exchange',
        'fiscal_year_end': 'fiscal_year_end',
        'fundamental_id': 'fundamental_id',
        'gic_group': 'gic_group',
        'gic_industry': 'gic_industry',
        'gic_sector': 'gic_sector',
        'home_category': 'home_category',
        'industry': 'industry',
        'international_domestic': 'international_domestic',
        'ipo_date': 'ipo_date',
        'is_delisted': 'is_delisted',
        'isin': 'isin',
        'name': 'name',
        'sector': 'sector',
        'stock_symbol': 'stock_symbol',
        'type': 'type'
    }

    def __init__(self, cik=None, country_name=None, currency=None, cusip=None, description=None, employer_id=None, exchange=None, fiscal_year_end=None, fundamental_id=None, gic_group=None, gic_industry=None, gic_sector=None, home_category=None, industry=None, international_domestic=None, ipo_date=None, is_delisted=None, isin=None, name=None, sector=None, stock_symbol=None, type=None, local_vars_configuration=None):  # noqa: E501
        """General - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cik = None
        self._country_name = None
        self._currency = None
        self._cusip = None
        self._description = None
        self._employer_id = None
        self._exchange = None
        self._fiscal_year_end = None
        self._fundamental_id = None
        self._gic_group = None
        self._gic_industry = None
        self._gic_sector = None
        self._home_category = None
        self._industry = None
        self._international_domestic = None
        self._ipo_date = None
        self._is_delisted = None
        self._isin = None
        self._name = None
        self._sector = None
        self._stock_symbol = None
        self._type = None
        self.discriminator = None

        if cik is not None:
            self.cik = cik
        if country_name is not None:
            self.country_name = country_name
        if currency is not None:
            self.currency = currency
        if cusip is not None:
            self.cusip = cusip
        if description is not None:
            self.description = description
        if employer_id is not None:
            self.employer_id = employer_id
        if exchange is not None:
            self.exchange = exchange
        if fiscal_year_end is not None:
            self.fiscal_year_end = fiscal_year_end
        if fundamental_id is not None:
            self.fundamental_id = fundamental_id
        if gic_group is not None:
            self.gic_group = gic_group
        if gic_industry is not None:
            self.gic_industry = gic_industry
        if gic_sector is not None:
            self.gic_sector = gic_sector
        if home_category is not None:
            self.home_category = home_category
        if industry is not None:
            self.industry = industry
        if international_domestic is not None:
            self.international_domestic = international_domestic
        if ipo_date is not None:
            self.ipo_date = ipo_date
        if is_delisted is not None:
            self.is_delisted = is_delisted
        if isin is not None:
            self.isin = isin
        if name is not None:
            self.name = name
        if sector is not None:
            self.sector = sector
        if stock_symbol is not None:
            self.stock_symbol = stock_symbol
        if type is not None:
            self.type = type

    @property
    def cik(self):
        """Gets the cik of this General.  # noqa: E501

        Company CIK Number  # noqa: E501

        :return: The cik of this General.  # noqa: E501
        :rtype: str
        """
        return self._cik

    @cik.setter
    def cik(self, cik):
        """Sets the cik of this General.

        Company CIK Number  # noqa: E501

        :param cik: The cik of this General.  # noqa: E501
        :type: str
        """

        self._cik = cik

    @property
    def country_name(self):
        """Gets the country_name of this General.  # noqa: E501

        the name of the country where the company is trading  # noqa: E501

        :return: The country_name of this General.  # noqa: E501
        :rtype: str
        """
        return self._country_name

    @country_name.setter
    def country_name(self, country_name):
        """Sets the country_name of this General.

        the name of the country where the company is trading  # noqa: E501

        :param country_name: The country_name of this General.  # noqa: E501
        :type: str
        """

        self._country_name = country_name

    @property
    def currency(self):
        """Gets the currency of this General.  # noqa: E501

        currency symbol under which the company financials are declared  # noqa: E501

        :return: The currency of this General.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this General.

        currency symbol under which the company financials are declared  # noqa: E501

        :param currency: The currency of this General.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def cusip(self):
        """Gets the cusip of this General.  # noqa: E501

        Company CUSIP number  # noqa: E501

        :return: The cusip of this General.  # noqa: E501
        :rtype: str
        """
        return self._cusip

    @cusip.setter
    def cusip(self, cusip):
        """Sets the cusip of this General.

        Company CUSIP number  # noqa: E501

        :param cusip: The cusip of this General.  # noqa: E501
        :type: str
        """

        self._cusip = cusip

    @property
    def description(self):
        """Gets the description of this General.  # noqa: E501

        Description of a company  # noqa: E501

        :return: The description of this General.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this General.

        Description of a company  # noqa: E501

        :param description: The description of this General.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def employer_id(self):
        """Gets the employer_id of this General.  # noqa: E501

        Company Employer ID  # noqa: E501

        :return: The employer_id of this General.  # noqa: E501
        :rtype: str
        """
        return self._employer_id

    @employer_id.setter
    def employer_id(self, employer_id):
        """Sets the employer_id of this General.

        Company Employer ID  # noqa: E501

        :param employer_id: The employer_id of this General.  # noqa: E501
        :type: str
        """

        self._employer_id = employer_id

    @property
    def exchange(self):
        """Gets the exchange of this General.  # noqa: E501

        the exchange_code the company has been listed under  # noqa: E501

        :return: The exchange of this General.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this General.

        the exchange_code the company has been listed under  # noqa: E501

        :param exchange: The exchange of this General.  # noqa: E501
        :type: str
        """

        self._exchange = exchange

    @property
    def fiscal_year_end(self):
        """Gets the fiscal_year_end of this General.  # noqa: E501

        Date of Companies fiscal year end  # noqa: E501

        :return: The fiscal_year_end of this General.  # noqa: E501
        :rtype: date
        """
        return self._fiscal_year_end

    @fiscal_year_end.setter
    def fiscal_year_end(self, fiscal_year_end):
        """Sets the fiscal_year_end of this General.

        Date of Companies fiscal year end  # noqa: E501

        :param fiscal_year_end: The fiscal_year_end of this General.  # noqa: E501
        :type: date
        """

        self._fiscal_year_end = fiscal_year_end

    @property
    def fundamental_id(self):
        """Gets the fundamental_id of this General.  # noqa: E501

        company unique id, used to create records related to this company details for example Highlights Information  # noqa: E501

        :return: The fundamental_id of this General.  # noqa: E501
        :rtype: str
        """
        return self._fundamental_id

    @fundamental_id.setter
    def fundamental_id(self, fundamental_id):
        """Sets the fundamental_id of this General.

        company unique id, used to create records related to this company details for example Highlights Information  # noqa: E501

        :param fundamental_id: The fundamental_id of this General.  # noqa: E501
        :type: str
        """

        self._fundamental_id = fundamental_id

    @property
    def gic_group(self):
        """Gets the gic_group of this General.  # noqa: E501

        The Global Industry Classification Standard Group  # noqa: E501

        :return: The gic_group of this General.  # noqa: E501
        :rtype: str
        """
        return self._gic_group

    @gic_group.setter
    def gic_group(self, gic_group):
        """Sets the gic_group of this General.

        The Global Industry Classification Standard Group  # noqa: E501

        :param gic_group: The gic_group of this General.  # noqa: E501
        :type: str
        """

        self._gic_group = gic_group

    @property
    def gic_industry(self):
        """Gets the gic_industry of this General.  # noqa: E501

        The Global Industry Classification Standard Industry  # noqa: E501

        :return: The gic_industry of this General.  # noqa: E501
        :rtype: str
        """
        return self._gic_industry

    @gic_industry.setter
    def gic_industry(self, gic_industry):
        """Sets the gic_industry of this General.

        The Global Industry Classification Standard Industry  # noqa: E501

        :param gic_industry: The gic_industry of this General.  # noqa: E501
        :type: str
        """

        self._gic_industry = gic_industry

    @property
    def gic_sector(self):
        """Gets the gic_sector of this General.  # noqa: E501

        The Global Industry Classification Standard sector  # noqa: E501

        :return: The gic_sector of this General.  # noqa: E501
        :rtype: str
        """
        return self._gic_sector

    @gic_sector.setter
    def gic_sector(self, gic_sector):
        """Sets the gic_sector of this General.

        The Global Industry Classification Standard sector  # noqa: E501

        :param gic_sector: The gic_sector of this General.  # noqa: E501
        :type: str
        """

        self._gic_sector = gic_sector

    @property
    def home_category(self):
        """Gets the home_category of this General.  # noqa: E501

        home category  # noqa: E501

        :return: The home_category of this General.  # noqa: E501
        :rtype: str
        """
        return self._home_category

    @home_category.setter
    def home_category(self, home_category):
        """Sets the home_category of this General.

        home category  # noqa: E501

        :param home_category: The home_category of this General.  # noqa: E501
        :type: str
        """

        self._home_category = home_category

    @property
    def industry(self):
        """Gets the industry of this General.  # noqa: E501

        The industry the company operates under  # noqa: E501

        :return: The industry of this General.  # noqa: E501
        :rtype: str
        """
        return self._industry

    @industry.setter
    def industry(self, industry):
        """Sets the industry of this General.

        The industry the company operates under  # noqa: E501

        :param industry: The industry of this General.  # noqa: E501
        :type: str
        """

        self._industry = industry

    @property
    def international_domestic(self):
        """Gets the international_domestic of this General.  # noqa: E501

        true if company operates internationally and domestically  # noqa: E501

        :return: The international_domestic of this General.  # noqa: E501
        :rtype: bool
        """
        return self._international_domestic

    @international_domestic.setter
    def international_domestic(self, international_domestic):
        """Sets the international_domestic of this General.

        true if company operates internationally and domestically  # noqa: E501

        :param international_domestic: The international_domestic of this General.  # noqa: E501
        :type: bool
        """

        self._international_domestic = international_domestic

    @property
    def ipo_date(self):
        """Gets the ipo_date of this General.  # noqa: E501

        Date of initial public offering  # noqa: E501

        :return: The ipo_date of this General.  # noqa: E501
        :rtype: date
        """
        return self._ipo_date

    @ipo_date.setter
    def ipo_date(self, ipo_date):
        """Sets the ipo_date of this General.

        Date of initial public offering  # noqa: E501

        :param ipo_date: The ipo_date of this General.  # noqa: E501
        :type: date
        """

        self._ipo_date = ipo_date

    @property
    def is_delisted(self):
        """Gets the is_delisted of this General.  # noqa: E501

        True if company is de_listed  # noqa: E501

        :return: The is_delisted of this General.  # noqa: E501
        :rtype: bool
        """
        return self._is_delisted

    @is_delisted.setter
    def is_delisted(self, is_delisted):
        """Sets the is_delisted of this General.

        True if company is de_listed  # noqa: E501

        :param is_delisted: The is_delisted of this General.  # noqa: E501
        :type: bool
        """

        self._is_delisted = is_delisted

    @property
    def isin(self):
        """Gets the isin of this General.  # noqa: E501

        Company ISIN number  # noqa: E501

        :return: The isin of this General.  # noqa: E501
        :rtype: str
        """
        return self._isin

    @isin.setter
    def isin(self, isin):
        """Sets the isin of this General.

        Company ISIN number  # noqa: E501

        :param isin: The isin of this General.  # noqa: E501
        :type: str
        """

        self._isin = isin

    @property
    def name(self):
        """Gets the name of this General.  # noqa: E501

        company name as registered in the place country listed  # noqa: E501

        :return: The name of this General.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this General.

        company name as registered in the place country listed  # noqa: E501

        :param name: The name of this General.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def sector(self):
        """Gets the sector of this General.  # noqa: E501

        The business sector the company operates in  # noqa: E501

        :return: The sector of this General.  # noqa: E501
        :rtype: str
        """
        return self._sector

    @sector.setter
    def sector(self, sector):
        """Sets the sector of this General.

        The business sector the company operates in  # noqa: E501

        :param sector: The sector of this General.  # noqa: E501
        :type: str
        """

        self._sector = sector

    @property
    def stock_symbol(self):
        """Gets the stock_symbol of this General.  # noqa: E501

        company stock_codes as listed in the stock exchange_code  # noqa: E501

        :return: The stock_symbol of this General.  # noqa: E501
        :rtype: str
        """
        return self._stock_symbol

    @stock_symbol.setter
    def stock_symbol(self, stock_symbol):
        """Sets the stock_symbol of this General.

        company stock_codes as listed in the stock exchange_code  # noqa: E501

        :param stock_symbol: The stock_symbol of this General.  # noqa: E501
        :type: str
        """

        self._stock_symbol = stock_symbol

    @property
    def type(self):
        """Gets the type of this General.  # noqa: E501

        company type  # noqa: E501

        :return: The type of this General.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this General.

        company type  # noqa: E501

        :param type: The type of this General.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, General):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, General):
            return True

        return self.to_dict() != other.to_dict()
