# ref: https://docs.gitlab.com/ee/ci/README.html

stages:
  - test

.nosetest:
  stage: test
  script:
   - pip install -r requirements.txt
   - pip install -r test-requirements.txt
   - pytest --cov=intelligentStockMarketAPI

nosetest-3.7:
  extends: .nosetest
  image: python:3.7-alpine
nosetest-3.8:
  extends: .nosetest
  image: python:3.8-alpine
