# coding: utf-8

"""
    EOD STOCK API

     <h2>Intelligent EOD Stocks API</h2>     <p>     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     <ul>         <li>Exchange Information</li>         <li>Stock Tickers Data</li>         <li>End of Day (EOD) Stock Data</li>         <li>Fundamental Data</li>         <li>Stock Options And Splits Data</li>         <li>Financial News API</li>         <li>Social Media Trend Data For Stocks</li>         <li>Sentiment Analysis for News & Social Media</li>     </ul>                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     </p>    # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@eod-stock-api.site
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "Intelligent-Stock-Market-API"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="An Intelligent EOD Stock Market, Financial News & Financial Social Media Trends API",
    author="MJ API Development",
    author_email="support@eod-stock-api.site",
    url="https://eod-stock-api.site",
    keywords=["OpenAPI", "Intelligent EOD Stock Market API", "EOD STOCK API", "Financial News API", "Financial Social Media Trends"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
     &lt;h2&gt;Intelligent EOD Stocks API&lt;/h2&gt;     &lt;p&gt;     End of day stock world wide STOCK API, this api is intended for use by web application developers,      and service providers looking for up-to-date always available.     &lt;ul&gt;         &lt;li&gt;Exchange Information&lt;/li&gt;         &lt;li&gt;Stock Tickers Data&lt;/li&gt;         &lt;li&gt;End of Day (EOD) Stock Data&lt;/li&gt;         &lt;li&gt;Fundamental Data&lt;/li&gt;         &lt;li&gt;Stock Options And Splits Data&lt;/li&gt;         &lt;li&gt;Financial News API&lt;/li&gt;         &lt;li&gt;Social Media Trend Data For Stocks&lt;/li&gt;         &lt;li&gt;Sentiment Analysis for News &amp; Social Media&lt;/li&gt;     &lt;/ul&gt;                The information provided covers more than 150 000 tickers, stocks, mutual funds and more around the world.         we provide information for any period, including daily, weekly.     &lt;/p&gt;    # noqa: E501
    """
)
